openapi: 3.0.3
info:
  title: API-CUBA
  description: 'API-CUBA Documentation'
  version: 1.0.0
servers:
  -
    url: ''
paths:
  /api/v1/search/municipalities-by-provinces:
    get:
      summary: 'Resource to search for the municipalities of a province'
      description: ''
      parameters:
        -
          in: query
          name: 'filter[provincie.name]'
          description: 'Name of the province to search'
          example: temporibus
          required: false
          schema:
            type: string
            description: 'Name of the province to search'
            example: temporibus
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '200{'
          content:
            text/plain:
              schema:
                type: string
                example: "\"data\": [\n   {\n     \"id\": 1,\n     \"name\": \"Arroyo Naranjo\"\n   },\n   {\n     \"id\": 2,\n     \"name\": \"Boyeros\"\n   },\n   {\n     \"id\": 3,\n     \"name\": \"Centro Habana\"\n   },\n   {\n     \"id\": 4,\n     \"name\": \"Cerro\"\n   },\n\n  ],\n   \"paginate\": {\n     \"current_page\": 1,\n     \"last_page\": 1,\n     \"per_page\": 15,\n     \"total\": 15\n   },\n   \"message\": \"15 de registros listados correctamente\"\n}"
      tags:
        - Search
      security: []
  /api/v1/search/neighborhoods-by-municipality:
    get:
      summary: "Resource to search for the neighborhoods of a municipality\nNote: This resource will be gradually implemented"
      description: ''
      parameters:
        -
          in: query
          name: 'filter[provincie.name]'
          description: 'Name of the province to search'
          example: dolores
          required: false
          schema:
            type: string
            description: 'Name of the province to search'
            example: dolores
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '200{'
          content:
            text/plain:
              schema:
                type: string
                example: "\"data\": [\n   {\n     \"id\": 1,\n     \"name\": \"Belen\"\n   },\n   {\n     \"id\": 2,\n     \"name\": \"Sitios\"\n   },\n   {\n     \"id\": 3,\n     \"name\": \"Jesus Maria\"\n   },\n   {\n     \"id\": 4,\n     \"name\": \"Atarei\"\n   },\n\n  ],\n   \"paginate\": {\n     \"current_page\": 1,\n     \"last_page\": 1,\n     \"per_page\": 15,\n     \"total\": 15\n   },\n   \"message\": \"15 de registros listados correctamente\"\n}"
      tags:
        - Search
      security: []
  /api/v1/municipalities:
    get:
      summary: 'Resource to get all municipalities'
      description: ''
      parameters:
        -
          in: query
          name: page
          description: 'The page number'
          example: 2
          required: false
          schema:
            type: integer
            description: 'The page number'
            example: 2
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 2
                    name: Julietville
                    provincia: null
                properties:
                  data:
                    type: object
                    example:
                      id: 2
                      name: Julietville
                      provincia: null
      tags:
        - Municipality
      security: []
    post:
      summary: 'Resource to store single municipality'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    {\n         \"data\": {\n             \"name\": \"Habana Vieja\",\n             \"updated_at\": \"2022-03-24T14:45:53.000000Z\",\n             \"created_at\": \"2022-03-24T14:45:53.000000Z\",\n             \"id\": 36\n         },\n         \"message\": \"El recurso se ha creado correctamente\"\n    }\n }"
        422:
          description: 'Unprocessable Content'
          content:
            text/plain:
              schema:
                type: string
                example: "{\n     {\n        \"errors\": [\n           \"El campo municipio debe ser único\"\n        ],\n        \"message\": \"Los parámetros no son válidos\"\n     }\n}"
      tags:
        - Municipality
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: sequi
                provincie_id:
                  type: integer
                  description: ''
                  example: 10
              required:
                - name
      security: []
  /api/v1/post-municipalities:
    post:
      summary: 'Resource to store a lot of municipalities'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    {\n      \"data\": true,\n      \"message\": \"El recurso se ha creado correctamente\"\n    }\n }"
        422:
          description: Unprocessable
          content:
            text/plain:
              schema:
                type: string
                example: "Content\n{\n   {\n     \"message\": \"Entrada duplicada\"\n   }\n}"
      tags:
        - Municipality
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: array
                  description: ''
                  example:
                    - fugiat
                  items:
                    type: string
                provincie_id:
                  type: integer
                  description: 'ID of province'
                  example: 8
              required:
                - name
      security: []
  /api/v1/post-neighborhoods:
    post:
      summary: 'Resource to store a lot of municipalities'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    {\n      \"data\": true,\n      \"message\": \"El recurso se ha creado correctamente\"\n    }\n }"
        422:
          description: 'Unprocessable Content'
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   {\n     \"message\": \"Entrada duplicada\"\n   }\n}"
      tags:
        - Neighborhood
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                municipalitie_id:
                  type: integer
                  description: 'ID of municipalities'
                  example: 17
                name:
                  type: array
                  description: ''
                  example:
                    - odit
                  items:
                    type: string
              required:
                - name
      security: []
  /api/v1/neighborhoods:
    get:
      summary: 'Resource to get all neighborhoods'
      description: ''
      parameters:
        -
          in: query
          name: page
          description: 'The number of page.'
          example: 2
          required: false
          schema:
            type: integer
            description: 'The number of page.'
            example: 2
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: null
                    name_neighborhood: 'South Deanna'
                properties:
                  data:
                    type: object
                    example:
                      id: null
                      name_neighborhood: 'South Deanna'
      tags:
        - Neighborhood
      security: []
    post:
      summary: 'Resource to store a single neighborhood'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    {\n         \"data\": {\n             \"name\": \"Belen\",\n             \"updated_at\": \"2022-03-24T14:45:53.000000Z\",\n             \"created_at\": \"2022-03-24T14:45:53.000000Z\",\n             \"id\": 36\n         },\n         \"message\": \"El recurso se ha creado correctamente\"\n    }\n }"
        422:
          description: 'Unprocessable Content'
          content:
            text/plain:
              schema:
                type: string
                example: "{\n     {\n        \"errors\": [\n           \"El campo barrio o consejo popular debe ser único\"\n        ],\n        \"message\": \"Los parámetros no son válidos\"\n     }\n}"
      tags:
        - Neighborhood
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: aut
                municipalitie_id:
                  type: integer
                  description: ''
                  example: 13
              required:
                - name
                - municipalitie_id
      security: []
  /api/v1/post-provincies:
    post:
      summary: 'Resource to store multiples provinces'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    {\n      \"data\": true,\n      \"message\": \"El recurso se ha creado correctamente\"\n    }\n }"
        422:
          description: 'Unprocessable Content'
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   {\n     \"message\": \"Entrada duplicada\"\n   }\n}"
      tags:
        - Province
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: array
                  description: ''
                  example:
                    - laborum
                  items:
                    type: string
              required:
                - name
      security: []
  /api/v1/provincies:
    get:
      summary: 'Display a listing of the resource.'
      description: ''
      parameters:
        -
          in: query
          name: page
          description: 'The page number.'
          example: 0
          required: false
          schema:
            type: integer
            description: 'The page number.'
            example: 0
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 4
                      name: 'Pinar del Rio'
                    -
                      id: 5
                      name: 'La Habana'
                    -
                      id: 6
                      name: 'Santiago de Cuba'
                  paginate:
                    current_page: 1
                    last_page: 1
                    per_page: 10
                    total: 3
                  message: '3 de registros listados correctamente'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 4
                        name: 'Pinar del Rio'
                      -
                        id: 5
                        name: 'La Habana'
                      -
                        id: 6
                        name: 'Santiago de Cuba'
                    items:
                      type: object
                  paginate:
                    type: object
                    example:
                      current_page: 1
                      last_page: 1
                      per_page: 10
                      total: 3
                  message:
                    type: string
                    example: '3 de registros listados correctamente'
      tags:
        - Province
      security: []
    post:
      summary: 'Resource to store a single province'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    {\n         \"data\": {\n             \"name\": \"La Habana\",\n             \"updated_at\": \"2022-03-24T14:45:53.000000Z\",\n             \"created_at\": \"2022-03-24T14:45:53.000000Z\",\n             \"id\": 36\n         },\n         \"message\": \"El recurso se ha creado correctamente\"\n    }\n }"
        422:
          description: 'Unprocessable Content'
          content:
            text/plain:
              schema:
                type: string
                example: "{\n     {\n        \"errors\": [\n           \"El campo provincia debe ser único\"\n        ],\n        \"message\": \"Los parámetros no son válidos\"\n     }\n }"
      tags:
        - Province
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: occaecati
              required:
                - name
      security: []
tags:
  -
    name: Search
    description: ''
  -
    name: Municipality
    description: ''
  -
    name: Neighborhood
    description: ''
  -
    name: Province
    description: ''
