openapi: 3.0.3
info:
  title: API_CUBA
  description: 'Documentación de API_CUBA'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/neighborhoods:
    get:
      summary: 'Display a listing of the resource.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 5
                      barrio: Belen
                      municipio:
                        id: 9
                        name: Guanabacoa
                        provincia:
                          id: 17
                          name: 'La Habana'
                  paginate:
                    current_page: 1
                    last_page: 1
                    per_page: 10
                    total: 1
                  message: '1 registros listados correctamente'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 5
                        barrio: Belen
                        municipio:
                          id: 9
                          name: Guanabacoa
                          provincia:
                            id: 17
                            name: 'La Habana'
                    items:
                      type: object
                  paginate:
                    type: object
                    example:
                      current_page: 1
                      last_page: 1
                      per_page: 10
                      total: 1
                  message:
                    type: string
                    example: '1 registros listados correctamente'
      tags:
        - 'Barrios o Consejos Populares'
      security: []
  /api/v1/municipalities:
    get:
      summary: 'Display a listing of the resource.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 9
                      name: Guanabacoa
                      provincia:
                        id: 17
                        name: 'La Habana'
                  paginate:
                    current_page: 1
                    last_page: 1
                    per_page: 10
                    total: 1
                  message: '1 registros listados correctamente'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 9
                        name: Guanabacoa
                        provincia:
                          id: 17
                          name: 'La Habana'
                    items:
                      type: object
                  paginate:
                    type: object
                    example:
                      current_page: 1
                      last_page: 1
                      per_page: 10
                      total: 1
                  message:
                    type: string
                    example: '1 registros listados correctamente'
      tags:
        - Municipios
      security: []
  /api/v1/provincies:
    get:
      summary: 'Display a listing of the resource.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 17
                      name: 'La Habana'
                  paginate:
                    current_page: 1
                    last_page: 1
                    per_page: 10
                    total: 1
                  message: '1 registros listados correctamente'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 17
                        name: 'La Habana'
                    items:
                      type: object
                  paginate:
                    type: object
                    example:
                      current_page: 1
                      last_page: 1
                      per_page: 10
                      total: 1
                  message:
                    type: string
                    example: '1 registros listados correctamente'
      tags:
        - Provincias
      security: []
tags:
  -
    name: 'Barrios o Consejos Populares'
    description: "\n Este endpoint estara disponible en versiones posteriores\n\n Listado de los barrios o consejos populares"
  -
    name: Municipios
    description: "\n Listado de los muncipios"
  -
    name: Provincias
    description: "\n Listado de las provincias"
